CREATE TABLE IF NOT EXISTS gerador_nd.user
(
    id         SERIAL PRIMARY KEY,
    username    VARCHAR(50) NOT NULL UNIQUE,
    emailVARCHAR(100) NOT NULL UNIQUE,
    password    VARCHAR(100) NOT NULL,
    email       VARCHAR(100) NOT NULL UNIQUE,
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);