UPDATE byd.db_compras_byd
SET
    percentil_atacado = NULLIF(percentil_atacado, 'NaN'),
    percentil_tiktok = NULLIF(percentil_tiktok, 'NaN'),
    percentil_nps = NULLIF(percentil_nps, 'NaN'),
    percentil_visits = NULLIF(percentil_visits, 'NaN'),
    percentil_snapon = NULLIF(percentil_snapon, 'NaN'),
    percentil_mystery = NULLIF(percentil_mystery, 'NaN'),
    percentil_chatbot = NULLIF(percentil_chatbot, 'NaN'),
    percentil_download = NULLIF(percentil_download, 'NaN'),
    tot_mercadoria = NULLIF(tot_mercadoria, 'NaN'),
    tot_custo_medio = NULLIF(tot_custo_medio, 'NaN'),
    val_base_ipi = NULLIF(val_base_ipi, 'NaN'),
    tot_ipi = NULLIF(tot_ipi, 'NaN'),
    tot_nota_fiscal = NULLIF(tot_nota_fiscal, 'NaN'),
    val_base_icms = NULLIF(val_base_icms, 'NaN'),
    val_icms = NULLIF(val_icms, 'NaN'),
    val_isento = NULLIF(val_isento, 'NaN'),
    val_outros_icms = NULLIF(val_outros_icms, 'NaN'),
    valdesconto = NULLIF(valdesconto, 'NaN'),
    val_base_iss = NULLIF(val_base_iss, 'NaN'),
    val_frete = NULLIF(val_frete, 'NaN'),
    val_seguro = NULLIF(val_seguro, 'NaN'),
    val_base_icm_retido = NULLIF(val_base_icm_retido, 'NaN'),
    val_pdi = NULLIF(val_pdi, 'NaN');